---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service-upstreams: 'catalog:8081,inventory:8082'
      labels:
        app: api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: 'reverseskate/consul-review-app-demo-api:${GIT_COMMIT_SHA}'
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
          env:
          - name: CATALOG_URL
            value: 'localhost:8081'
          - name: INVENTORY_URL
            value: 'localhost:8082'
