---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: catalog
    spec:
      serviceAccountName: catalog
      containers:
        - name: catalog
          image: 'reverseskate/consul-review-app-demo-catalog:${GIT_COMMIT_SHA}'
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
          env:
          - name: PORT
            value: "3000"
