---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: inventory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: inventory
    spec:
      serviceAccountName: inventory
      containers:
        - name: inventory
          image: 'reverseskate/consul-review-app-demo-inventory:${GIT_COMMIT_SHA}'
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
